# Generated by Django 5.2.3 on 2025-06-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handle_face', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Face',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
